### ISSUE TITLE
[Feature] Show Desktop Notifications

### ISSUE THREAD

**Issue by xrelkd** [xrelkd/clipcat#130]
Show desktop notifications for the following events:
- on daemon started (message: `Server is running`)
- on daemon captured shutdown signal (message: `Server is shutting down`)
- on clipboard history cleared (message: `Clipboard history is cleared`)
- on watcher enabled (message: `Watcher is enabled`)
- on watcher disabled (message: `Watcher is disabled`)

Configuration:

```toml
[desktop_notification]
enable = true
icon = "/path/to/the/icon"      # use `accessories-clipboard` as default
timeout_ms = 1000
```

Rust crate:
- https://crates.io/crates/notify-rust
- https://docs.rs/notify-rust/latest/notify_rust/index.html
